"""empty message

Revision ID: fec14ed04a7d
Revises: 4926645baaf3
Create Date: 2023-03-07 23:15:15.057249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec14ed04a7d'
down_revision = '4926645baaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('color_de_pelo', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('peso', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('height', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=100), nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('diameter', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('terrain')
        batch_op.drop_column('gravity')
        batch_op.drop_column('population')
        batch_op.drop_column('diameter')
        batch_op.drop_column('climate')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('height')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('peso')
        batch_op.drop_column('color_de_pelo')
        batch_op.drop_column('genero')

    # ### end Alembic commands ###
